services:
    security.access.card_voter:
        class:      AppBundle\Security\Authorization\Voter\CardVoter
        public:     false
        tags:
           - { name: security.voter }
    app.twig_extension:
        class: AppBundle\Twig\VariousExtension
        public: false
        tags:
            - { name: twig.extension }

    app.generate:
        class: AppBundle\Service\GenerateService
        arguments: ["@doctrine.orm.entity_manager", "@monolog.logger.pdf", "@templating", "@knp_snappy.pdf"]

    app.cardListener:
        class: AppBundle\EventListener\CardListener
        arguments: ["@monolog.logger.listener"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
